### ISSUE TITLE
output and save

### ISSUE THREAD

**Issue by Egida** [DrankRock/ProxyScrape-And-Check#2]
Hi, problem with save proxy:
`└─# python3 ProxyScrape.py        
Starting ProxyScrape with parameters :
--- Threads : 50
--- Website : https://www.google.com/
--- Timeout : 10.0

Traceback (most recent call last):
  File "/root/Desktop/proxyscrape/ProxyScrape-And-Check/ProxyScrape.py", line 111, in outputFileDialog
    self.chosenOutLbl.setText(str(fileName))
AttributeError: 'MainWindow' object has no attribute 'chosenOutLbl'
zsh: IOT instruction  python3 ProxyScrape.py

`

**Comment by DrankRock** [comment]
Alright I actually forgot to implement that .. 

I'll do that ASAP, thanks for the issue !

Edit : Input now works, output needs to be done !

**Comment by Egida** [comment]
> Alright I actually forgot to implement that ..
> 
> I'll do that ASAP, thanks for the issue !
> 
> Edit : Input now works, output needs to be done !

not work for me

`└─# python ProxyScrape.py    
Graphical Version
Starting ProxyScrape with parameters :
--- Threads : 50
--- Website : https://www.google.com/
--- Timeout : 10.0

Traceback (most recent call last):
  File "/root/Desktop/ProxyScrape-And-Check/ProxyScrape.py", line 128, in outputFileDialog
    self.chosenOutLbl.setText(str(fileName))
AttributeError: 'MainWindow' object has no attribute 'chosenOutLbl'
zsh: IOT instruction  python ProxyScrape.py
                                                 
`

**Comment by DrankRock** [comment]
> > Alright I actually forgot to implement that ..
> > I'll do that ASAP, thanks for the issue !
> > Edit : Input now works, output needs to be done !
> 
> not work for me
> 
> `└─# python ProxyScrape.py Graphical Version Starting ProxyScrape with parameters : --- Threads : 50 --- Website : https://www.google.com/ --- Timeout : 10.0
> 
> Traceback (most recent call last): File "/root/Desktop/ProxyScrape-And-Check/ProxyScrape.py", line 128, in outputFileDialog self.chosenOutLbl.setText(str(fileName)) AttributeError: 'MainWindow' object has no attribute 'chosenOutLbl' zsh: IOT instruction python ProxyScrape.py
> 
> `

It should be working now, please tell me if it works.

Next update will be a way to open GUI version with parameters applicating to it, as an example, if I do `python ProxyScrape.py -o output.txt -th 100`, the GUI will load with threads at 100, and an output already chosen.

And after that, a way to modify the default values.
